USE [AdvantageDB]
GO

INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (1, 1)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (1, 2)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (1, 6)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (1, 7)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (2, 1)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (2, 8)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (2, 9)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (3, 10)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (3, 11)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (4, 12)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (4, 13)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (4, 14)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (5, 12)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (5, 13)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (6, 12)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (6, 14)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (7, 7)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (7, 1)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (7, 4)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (7, 6)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (8, 15)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (8, 16)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (8, 17)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (9, 18)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (9, 19)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (9, 20)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (10, 21)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (10, 22)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (10, 23)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (11, 24)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (11, 25)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (12, 24)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (12, 25)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (12, 5)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (13, 1)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (13, 2)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (13, 7)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (13, 8)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (13, 6)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (13, 4)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (13, 9)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (14, 26)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (14, 27)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (15, 28)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (15, 29)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (15, 30)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (15, 31)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (16, 32)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (16, 33)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (16, 34)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (17, 34)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (17, 35)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (17, 36)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (18, 12)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (18, 30)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (18, 34)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (19, 37)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (19, 20)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (20, 12)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (20, 34)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (20, 38)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (20, 39)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (21, 40)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (21, 41)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (21, 42)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (22, 43)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (22, 44)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (23, 45)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (23, 46)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (23, 47)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (24, 45)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (24, 48)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (24, 49)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (24, 50)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (25, 51)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (26, 12)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (26, 34)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (26, 44)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (27, 11)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (27, 52)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (27, 53)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (27, 54)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (27, 55)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (27, 10)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (28, 56)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (28, 57)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (28, 58)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (29, 59)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (29, 60)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (29, 61)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (30, 62)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (30, 21)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (31, 62)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (31, 21)
INSERT [dbo].[PromoterTags] ([PromoterID], [TagID]) VALUES (31, 63)











