USE [AdvantageDB]
GO

INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'julyos.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'kafalu.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'libreriajosue.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'milanezaclub.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'mueladeldiablo.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'patatabrava.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'petra.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'pil.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'rubsor.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'puertonatura.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'spicy.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'tonnysburguer.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'topcollection.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'totto.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'wistupiku.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'zonadehumor.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'bcdtravel.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'castores.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'ciacruz.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'clementina.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'comteco.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'cortijo.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'crazystore.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'dismac.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'eskaparate.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'factorygrill.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'fulloffice.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'gosport.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'homecenter.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'hotelcochabamba.advantage@gmail.com', N'admin123aaa', 2)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'hotelcolonia.advantage@gmail.com', N'admin123aaa', 2)

INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'gabriel.gomez@jalasoft.com', N'admin123aaa', 3)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'raul.artero@jalasoft.com', N'admin123aaa', 3)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'amalia.alfaro@jalasoft.com', N'admin123aaa', 3)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'diego.gomez@jalasoft.com', N'admin123aaa', 3)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'lineth.zurita@jalasoft.com', N'admin123aaa', 3)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'adriana.cors@jalasoft.com', N'admin123aaa', 3)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'mica.delgadillo@jalasoft.com', N'admin123aaa', 3)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'carlos.games@jalasoft.com', N'admin123aaa', 3)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'silvana.soruco@jalasoft.com', N'admin123aaa', 3)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'sara.villanueva@jalasoft.com', N'admin123aaa', 3)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'andrea.parra@jalasoft.com', N'admin123aaa', 3)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'olivia.manicone@jalasoft.com', N'admin123aaa', 3)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'ilsen.noriega@jalasoft.com', N'admin123aaa', 3)

INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'coordinator.advantage@jalasoft.com', N'admin123aaa', 1)
INSERT [dbo].[Users] ([Email], [Password], [RoleId]) VALUES (N'carlos.roman@jalasoft.com', N'admin123aaa', 1)