USE [AdvantageDB]
GO

INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Daniel Mamani', 72236599, N'daniel@julyos.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Gustavo Rodriguez', 76485963, N'gustavo@kafalu.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Noelia Lopez', 70745022, N'noelia@libreria-josue.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Pamela Quispe', 67588969, N'juan@milaneza-club.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Marcela Odonto', 72256123, N'juan@muela-diablo.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Alberto Miranda', 76987445, N'juan@patata-brava.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Orlando Santander', 77522563, N'juan@petra.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Paola Mejia', 76450236, N'juan@pil.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Javier Terceros', 70758966, N'juan@rubsor.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Diego Rivas', 67589145, N'juan@sauna-puerto-natura.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Ariel Cardenas', 76758966, N'juan@spicy.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Karen Larrea', 76914785, N'juan@tonnys-burguer.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Andrea Crespo', 72234704, N'juan@top-collection.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Julio Campos', 70736885, N'juan@totto.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Mauricio Ventura', 71489257, N'juan@wistupiku.com')
INSERT [dbo].[Contacts] ([Name], [Phone], [Email]) VALUES (N'Gaia Antezana', 76952478, N'juan@zona-humor.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Juan Orellana', 79649888, N'juan@bcd.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Jose Ecos', 75649888, N'jose@castores.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Carlos Medrano', 66649888, N'carlos@ciacruz.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Pablo Flores', 79646548, N'pablo@clementina.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Jorge Delgado', 79665487, N'jorge@comteco.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Horacio Delgadillo', 73548887, N'horacio@cortijo.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Manuel Lopez', 79646587, N'manuel@crazy-store.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Fabricio Sanchez', 79498887, N'fabricio@dismac.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Betty Rodriguez', 79611117, N'betty@eskaparate.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Daniela Villanueva', 69898887, N'daniela@factory.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Paola Velasquez', 68964987, N'paola@full-office.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Gabriela Rios', 75498887, N'gabriela@go-office.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Aldo Pardo', 79654867, N'aldo@home-center.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Pedro Robles', 71659887, N'pedro@hotel-cochabamba.com')
INSERT [dbo].[Contacts] ([Name], [Phone] ,[Email]) VALUES (N'Jesus Sandoval', 79649367, N'jesus@hotel-colonia.com')
