USE [AdvantageDB]
GO

INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Julyos', 1, 4, 1, 1)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Kafalu', 2, 4, 2, 2)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Libreria Josue', 3, 2, 3, 3)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Milaneza Club', 4, 6, 4, 4)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Muela del Diablo', 5, 6, 5, 5)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Patata Brava', 6, 6, 6, 6)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Petra', 7, 4, 7, 7)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Pil', 8, 10, 8, 8)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Rubsor Mecanica Automotriz', 9, 3, 9, 9)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Sauna Puerto Natura', 10, 9, 10, 10)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Spicy', 11, 6, 11, 11)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Tonnys Burguer', 12, 6, 12, 12)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Top Collection', 13, 4, 13, 13)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Totto', 14, 4, 14, 14)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Wistupiku', 15, 6, 15, 15)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Zona de Humor', 16, 11, 16, 16)

INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'BCD Travel', 17, 8, 17, 17)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Los Castores', 18, 6, 18, 18)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'La Ciacruz', 19, 3, 19, 19)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Clementina', 20, 6, 20, 20)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Comteco', 21, 10, 21, 21)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'El cortijo', 22, 5, 22, 22)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Crazy Store', 23, 10, 23, 23)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Dismac', 24, 10, 24, 24)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Eskaparate', 25, 4, 25, 25)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Factory', 26, 6, 26, 26)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Full Office', 27, 2, 27, 27)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'GoTwoSport', 28, 4, 28, 28)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Home Center', 29, 10, 29, 29)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Hotel Cochabamba', 30, 1, 30, 30)
INSERT [dbo].[Promoters] ([Name], [ImageID], [CategoryID], [ContactID], [UserID]) VALUES (N'Hotel La Colonia', 31, 1, 31, 31)
