USE [AdvantageDB]
GO

INSERT [dbo].[Tags] ([Name]) VALUES (N'MODA')
INSERT [dbo].[Tags] ([Name]) VALUES (N'ROPA')
INSERT [dbo].[Tags] ([Name]) VALUES (N'SALCHIPAPAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'CAMISAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'HAMBURGUESAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'TERNOS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'HOMBRES')
INSERT [dbo].[Tags] ([Name]) VALUES (N'MUJERES')
INSERT [dbo].[Tags] ([Name]) VALUES (N'CARTERAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'LIBROS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'MATERIAL ESCOLAR')
INSERT [dbo].[Tags] ([Name]) VALUES (N'COMIDA')
INSERT [dbo].[Tags] ([Name]) VALUES (N'ALMUERZO')
INSERT [dbo].[Tags] ([Name]) VALUES (N'PAPAS FRITAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'YOGURT')
INSERT [dbo].[Tags] ([Name]) VALUES (N'LECHE')
INSERT [dbo].[Tags] ([Name]) VALUES (N'LACTEOS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'MOTOR')
INSERT [dbo].[Tags] ([Name]) VALUES (N'FRENOS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'AUTOS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'PISCINA')
INSERT [dbo].[Tags] ([Name]) VALUES (N'MASAJES')
INSERT [dbo].[Tags] ([Name]) VALUES (N'RELAX')
INSERT [dbo].[Tags] ([Name]) VALUES (N'ALITAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'COSTILLITAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'MOCHILAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'ROPA DEPORTIVA')
INSERT [dbo].[Tags] ([Name]) VALUES (N'EMPANADAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'API')
INSERT [dbo].[Tags] ([Name]) VALUES (N'SALTEÑAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'TUCUMANAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'HUMOR')
INSERT [dbo].[Tags] ([Name]) VALUES (N'ENTRENENIMIENTO')
INSERT [dbo].[Tags] ([Name]) VALUES (N'FAMILIA')
INSERT [dbo].[Tags] ([Name]) VALUES (N'VACACIONES')
INSERT [dbo].[Tags] ([Name]) VALUES (N'VIAJE')
INSERT [dbo].[Tags] ([Name]) VALUES (N'SEGUROS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'PAREJA')
INSERT [dbo].[Tags] ([Name]) VALUES (N'CENAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'SERVICIOS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'INTERNET')
INSERT [dbo].[Tags] ([Name]) VALUES (N'CABLE')
INSERT [dbo].[Tags] ([Name]) VALUES (N'BAR')
INSERT [dbo].[Tags] ([Name]) VALUES (N'BEBIDAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'TECNOLOGIA')
INSERT [dbo].[Tags] ([Name]) VALUES (N'LAPTOP')
INSERT [dbo].[Tags] ([Name]) VALUES (N'COMPUTADORA')
INSERT [dbo].[Tags] ([Name]) VALUES (N'TELEVISORES')
INSERT [dbo].[Tags] ([Name]) VALUES (N'LED')
INSERT [dbo].[Tags] ([Name]) VALUES (N'HD')
INSERT [dbo].[Tags] ([Name]) VALUES (N'ZAPATOS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'CUADERNOS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'LAPICES')
INSERT [dbo].[Tags] ([Name]) VALUES (N'COLORES')
INSERT [dbo].[Tags] ([Name]) VALUES (N'HOJAS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'DEPORTE')
INSERT [dbo].[Tags] ([Name]) VALUES (N'MOTOS')
INSERT [dbo].[Tags] ([Name]) VALUES (N'BICICLETA')
INSERT [dbo].[Tags] ([Name]) VALUES (N'CASA')
INSERT [dbo].[Tags] ([Name]) VALUES (N'MUEBLES')
INSERT [dbo].[Tags] ([Name]) VALUES (N'HOGAR')
INSERT [dbo].[Tags] ([Name]) VALUES (N'HOTEL')
INSERT [dbo].[Tags] ([Name]) VALUES (N'HABITACIONES')










