// <auto-generated/>
namespace JalaFoundation.Advantage.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddMainTextInBenefitModel : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Benefits", "MainText", c => c.String(nullable: false, maxLength: 90, unicode: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.Benefits", "MainText");
        }
    }
}
