// <auto-generated/>
namespace JalaFoundation.Advantage.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddRelationshipBetweenPromoterAndBenefit : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Benefits", "PromoterId", c => c.Int(nullable: false));
            CreateIndex("dbo.Benefits", "PromoterId");
            AddForeignKey("dbo.Benefits", "PromoterId", "dbo.Promoters", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Benefits", "PromoterId", "dbo.Promoters");
            DropIndex("dbo.Benefits", new[] { "PromoterId" });
            DropColumn("dbo.Benefits", "PromoterId");
        }
    }
}
